export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const CLEAR_AUTH_STATE = 'CLEAR_AUTH_STATE';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_CONTACTS_LOADING = 'GET_CONTCATS_LOADING';
export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILED = 'GET_CONTACTS_FAILED';

export const CREATE_CONTACT_LOADING = 'CREATE_CONTACT_LOADING ';
export const CREATE_CONTACT_SUCCESS = 'CREATE_CONTACT_SUCCESS';
export const CREATE_CONTACT_FAILED = 'CREATE_CONTACT_FAILED';

export const GET_CONTACT_DETAILS_LOADING = 'GET_CONTCAT_DETAILS_LOADING';
export const GET_CONTACT_DETAILS_SUCCESS = 'GET_CONTACT_DETAIL_SUCCESS';
export const GET_CONTACT_DETAILS_FAILED = 'GET_CONTACS_DETAILS_FAILED';

export const EDIT_CONTACT_SUCCESS = 'EDIT_CONTACT_SUCCESS';
export const EDIT_CONTACT_FAILED = 'EDIT_CONTACT_FAILED';
export const EDIT_CONTACT_LOADING = 'EDIT_CONTACT_LOADING ';

export const DELETE_CONTACT_LOADING = 'DELETE_CONTACT_LOADING ';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILED = 'DELETE_CONTACT_FAILED';
